[package]
org = "ballerinax"
name = "financial.iso20022.payments_clearing_and_settlement"
version = "1.0.0"
distribution = "2201.10.1"
authors=["Ballerina"]
export=["financial.iso20022.payments_clearing_and_settlement"]
keywords=["Financial", "ISO20022", "Payments Clearing", "Payments Settlement"]
repository="https://github.com/ballerina-platform/module-ballerinax-financial.iso20022"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
